# Spring Boot backend
# URL: http://localhost:8080/backend/

server.port=8080
server.servlet.context-path=/backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_pc
spring.datasource.username=postgres
spring.datasource.password=khalil
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=20MB

# JWT
app.jwt-secret=SECRET_KEY_123
app.jwt-expiration-seconds=3600

# Uploaded images
app.upload-dir=images